### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by antoinedeschenes** [Gandem/bonjour-reflector#20]
CPU usage seems to be quite high, I compiled bonjour-reflector on MIPS architecture and I get 100% load (of course it's not a very powerful CPU to start with...). I'm wondering if packet processing could be threaded, source VLANs filtered earlier or something.

**Comment by Gandem** [comment]
Thank you for your interest in this project !

I grabbed a quick cpu profile of a running application : 

![cgo](https://user-images.githubusercontent.com/11560964/37831610-73c25a6a-2ea6-11e8-8b1c-540900e00018.jpg)

What is taking the large majority of the cpu time is the packet capture with pcap. This definitely needs a more thorough investigation.

**Comment by antoinedeschenes** [comment]
I see, I built a version using afpacket instead of libpcap earlier this week but didn't try it yet on a VLAN trunk. (At least I saw some logs going on my home network)

**Comment by Gandem** [comment]
This should be fixed, as we updated `gopacket` so we can benefit from https://github.com/google/gopacket/commit/fa2cf54d72acd452a072ef005e231b5d7a7b5ebd

If you still have any problem, please feel free to reopen the issue !

**Comment by antoinedeschenes** [comment]
Hi, this seems to work really well, CPU usage has gone from 100% to <1%. 
My afpacket tests turned out to work on x86 but didn't work at all on the mips router

**Comment by L3Nerd** [comment]
Hey there,

I'm running bonjour-reflector on a homeserver with constant network-load on a single interface. 
The server traffic is running on the interface with an untagged vlan and all wifi-vlans are transmitted tagged to the server.

An average of approx. 70MBit/s  is running constantly through that interface, causing an average 20% load on the bonjour-reflector process.

Was anyone investigating on that issue further since last year?

**Comment by L3Nerd** [comment]
Nevermind - PR#23 seems to resolve that issue, will use that until merging.

**Comment by antoinedeschenes** [comment]
In my case the gopacket update on master was sufficient, but I was running bonjour-reflector on a separate interface passively listening for multicast  traffic
